[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "PyDatagramDB"
version = "0.0.3"
dependencies = ["networkx>=3.0","pandas>=2.0.0"]


[tool.scikit-build]
wheel.packages = ["DatagramDB/python/src/PyDatagramDB"]
cmake.build-type = "Release"
cmake.source-dir = "."
cmake.verbose = true
